# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
sudo: required
language: java
cache:
  directories:
  - $HOME/.cache
jdk:
- oraclejdk7
notifications:
  email: false
env:
  global:
     - REGRESSION_CYCLE=4
     - REGRESSION_INDEX=6
  matrix:
    - TESTS="smoke/test_affinity_groups smoke/test_primary_storage"
before_install: 
  - pip install codecov
  - travis_wait 30 ./tools/travis/before_install.sh
install: ./tools/travis/install.sh
before_script: travis_wait 30 ./tools/travis/before_script.sh
script:
  - travis_wait 30 sleep 30
  - ./tools/travis/script.sh $TESTS
after_success: 
  -  codecov
  - ./tools/travis/after_success.sh
after_failure: 
  - codecov
  - ./tools/travis/after_failure.sh
after_script: 
  - codecov
  - ./tools/travis/after_script.sh
